export const GET_CATEGORIES_START = 'GET_CATEGORIES_START'
export const GET_CATEGORIES_STOP = 'GET_CATEGORIES_STOP'
export const GET_CATEGORIES_PAYLOAD = 'GET_CATEGORIES_PAYLOAD'

export const NEW_CATEGORY_PLACEHOLDER = 'NEW_CATEGORY_PLACEHOLDER'
export const SHOW_CATEGORY = 'SHOW_CATEGORY'
export const CANCEL_NEW_CATEGORY = 'CANCEL_NEW_CATEGORY'

export const SUBMIT_NEW_CATEGORY_START = 'SUBMIT_NEW_CATEGORY_START'
export const SUBMIT_NEW_CATEGORY_STOP = 'SUBMIT_NEW_CATEGORY_STOP'
export const SUBMIT_NEW_CATEGORY_PAYLOAD = 'SUBMIT_NEW_CATEGORY_PAYLOAD'

export const GET_ALL_ENTRIES_START = 'GET_ALL_ENTRIES_START'
export const GET_ALL_ENTRIES_STOP = 'GET_ALL_ENTRIES_STOP'
export const GET_ALL_ENTRIES_PAYLOAD = 'GET_ALL_ENTRIES_PAYLOAD'

export const UPDATE_ADD_ENTRY = 'UPDATE_ADD_ENTRY'
export const SUBMIT_NEW_ENTRY_START = 'SUBMIT_NEW_ENTRY_START'
export const SUBMIT_NEW_ENTRY_STOP = 'SUBMIT_NEW_ENTRY_STOP'
export const SUBMIT_NEW_ENTRY_PAYLOAD = 'SUBMIT_NEW_ENTRY_PAYLOAD'
