export const GET_CATEGORIES = 'GET_CATEGORIES'
export const NEW_CATEGORY_PLACEHOLDER = 'NEW_CATEGORY_PLACEHOLDER'
export const SHOW_CATEGORY = 'SHOW_CATEGORY'
export const SUBMIT_NEW_CATEGORY = 'SUBMIT_NEW_CATEGORY'
export const CANCEL_NEW_CATEGORY = 'CANCEL_NEW_CATEGORY'

export const GET_ALL_ENTRIES = 'GET_ALL_ENTRIES'

export const UPDATE_ADD_ENTRY = 'UPDATE_ADD_ENTRY'
export const SUBMIT_NEW_ENTRY = 'SUBMIT_NEW_ENTRY'
